@PlatformService_HostAddress = http://localhost:5143

GET {{PlatformService_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{PlatformService_HostAddress}}/api/platforms

###
GET {{PlatformService_HostAddress}}/api/platforms/1

###
POST {{PlatformService_HostAddress}}/api/platforms/
Content-Type: application/json

{
  "name": "JS",
  "publisher": "Aaryan Baral",
  "cost": "Free"
}

